name: Create pull

description: Creates a pull reuqest

inputs:
  base:
    description: The base branch
    required: true
  head:
    description: The head branch
    required: true
  title:
    description: The title of the pull request
    required: true
outputs:
  pull_number:
    description: The pull request number
    value: ${{ steps.create-pull.outputs.pull_number }}

runs:
  using: composite
  steps:
    - name: Debug information
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        ENV_CONTEXT: ${{ toJSON(env) }}
        JOB_CONTEXT: ${{ toJSON(job) }}
        STEPS_CONTEXT: ${{ toJSON(steps) }}
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: env

    - name: Creating pull request
      id: create-pull
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.github_token }}
        script: |
          const { data: pullRequest } = await github.rest.pulls.create({
            owner: '${{ github.event.repository.owner.login }}',
            repo: '${{ github.event.repository.name }}',
            base: '${{ inputs.base }}',
            head: '${{ inputs.head }}',
            title: '${{ inputs.title }}',
            body: '',
            commit_message: '${{ inputs.title }}',
          })

          core.setOutput('pull_number', pullRequest.number);
