name: Merge pull

description: Creates a pull reuqest

inputs:
  pull_number:
    description: The pull request number
    required: true
  merge_method:
    description: 'The merge method to use. Valid values are:
      github_merge, github_squash, github_rebase, rebase'
    required: false
    default: 'rebase'
  delete_head:
    description: Delete the head branch after merge
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Merging pull request
      uses: actions/github-script@v6
      with:
        script: |
          const owner = '${{ github.event.repository.owner.login }}'
          const repo = '${{ github.event.repository.name }}'

          const { data: pullRequest } = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: ${{ inputs.pull_number }}
          })

          console.log('Merging pull request #${{ inputs.pull_number }}')

          let merge_method = '${{ inputs.merge_method }}'
          const isCustomRebase = merge_method === 'rebase'
          merge_method = isCustomRebase ? 'merge' : merge_method.replace(/^github_/, '')

          await github.rest.pulls.merge({
            owner,
            repo,
            pull_number: pullRequest.number,
            merge_method
          })

          if (isCustomRebase) {
            console.log('Using custom rebase strategy')

            const { data: headRef } = await github.rest.git.getRef({
              owner,
              repo,
              ref: `heads/${pullRequest.head.ref}`
            })

            console.log('Deleting merge commit ...')

            await github.rest.git.updateRef({
              owner,
              repo,
              ref: `heads/${pullRequest.base.ref}`,
              sha: headRef.object.sha,
              force: true
            })

            console.log('Successfully deleted merge commit')
          }

          if ('${{ inputs.delete_head }}' === 'true') {
            console.log('Deleting head branch ...')

            await github.rest.git.deleteRef({
              owner,
              repo,
              ref: `heads/${pullRequest.head.ref}`
            })

            console.log(`Successfully deleted head branch. Was ${pullRequest.head.ref}`)
          }
