name: Merge pull main

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: The pull request number to merge
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the repository
        uses: actions/checkout@v3

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          ENV_CONTEXT: ${{ toJSON(env) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
          INPUTS_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "Done"

      - name: Running tests
        run: |
          sleep 4 && echo "Success"

      # - name: Merging pull request
      #   uses: ./.github/actions/merge-pull
