name: Test

on:
  push:
    branches:
      - develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the repository
        uses: actions/checkout@v3

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}

      - name: Fail
        run: exit 1
